apiVersion: v1
name: mc-router
version: 1.2.6
appVersion: 1.20.0
home: https://github.com/itzg/mc-router
description: Routes Minecraft client connections to backend servers based upon the requested server address.
keywords:
  - minecraft
  - router
sources:
  - https://github.com/itzg/minecraft-server-charts
maintainers:
  - name: gtaylor
    email: gtaylor@gc-taylor.com
  - name: billimek
    email: jeff@billimek.com
  - name: itzg
    email: itzgeoff@gmail.com
  - name: bibz87
    email: yannik@carbongem.com
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/itzg/mc-router
    - name: Image DockerHub
      url: https://hub.docker.com/r/itzg/mc-router
