apiVersion: v1
name: minecraft
version: 4.26.4
appVersion: SeeValues
home: https://minecraft.net/
description: Minecraft server
keywords:
  - game
  - server
sources:
  - https://github.com/itzg/minecraft-server-charts
maintainers:
  - name: gtaylor
    email: gtaylor@gc-taylor.com
  - name: billimek
    email: jeff@billimek.com
  - name: itzg
    email: itzgeoff@gmail.com
  - name: bibz87
    email: yannik@carbongem.com
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/itzg/docker-minecraft-server
    - name: Image DockerHub
      url: https://hub.docker.com/r/itzg/minecraft-server
