apiVersion: v1
name: minecraft
version: 2.0.8
appVersion: SeeValues
home: https://minecraft.net/
description: Minecraft server
keywords:
- game
- server
sources:
- https://github.com/itzg/minecraft-server-charts
- https://hub.docker.com/r/itzg/minecraft-server/~/dockerfile/
- https://github.com/itzg/docker-minecraft-server
- https://github.com/itzg/docker-minecraft-bedrock-server
maintainers:
- name: gtaylor
  email: gtaylor@gc-taylor.com
- name: billimek
  email: jeff@billimek.com
- name: itzg
  email: itzgeoff@gmail.com
