apiVersion: v1
name: minecraft-bedrock
version: 2.1.2
appVersion: SeeValues
home: https://minecraft.net/
description: Minecraft server
keywords:
- game
- server
sources:
- https://github.com/itzg/minecraft-server-charts
maintainers:
- name: gtaylor
  email: gtaylor@gc-taylor.com
- name: billimek
  email: jeff@billimek.com
- name: itzg
  email: itzgeoff@gmail.com
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/itzg/docker-minecraft-bedrock-server
    - name: Image DockerHub
      url: https://hub.docker.com/r/itzg/minecraft-bedrock-server
