apiVersion: v1
name: minecraft-bedrock
version: 1.1.6
appVersion: 1.16
home: https://minecraft.net/
description: Minecraft server
keywords:
- game
- server
sources:
- https://github.com/itzg/minecraft-server-charts
- https://hub.docker.com/r/itzg/minecraft-bedrock-server/~/dockerfile/
- https://github.com/itzg/dockerfiles
maintainers:
- name: gtaylor
  email: gtaylor@gc-taylor.com
- name: billimek
  email: jeff@billimek.com
- name: itzg
  email: itzgeoff@gmail.com
