# ref: https://hub.docker.com/r/itzg/minecraft-server/
image: itzg/minecraft-bedrock-server
imageTag: latest

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 500m

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}

# Most of these map to environment variables. See Minecraft for details:
# https://hub.docker.com/r/itzg/minecraft-server/
livenessProbe:
  initialDelaySeconds: 30
readinessProbe:
  initialDelaySeconds: 30
minecraftServer:
  # This must be overridden, since we can't accept this for the user.
  eula: "FALSE"
  # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
  version: "1.14.4"
  # One of: peaceful, easy, normal, and hard
  difficulty: easy
  # A comma-separated list of player names to whitelist.
  whitelist:
  # Max connected players.
  maxPlayers: 20
  # The world is ticked this many chunks away from any player.
  tickDistance : 4
  # Max view distance (in chunks).
  viewDistance: 10
  # The "level-name" value is used as the world name and its folder name. The player may also copy their saved game folder here, and change the name to the same as that folder's to load it instead.
  levelName: K8sLevel
  # Define this if you want a specific map generation seed.
  levelSeed:
  # One of: creative, survival, adventure, spectator
  gameMode: survival
  # Permission level for new players joining for the first time.
  defaultPermission: member
  # After a player has idled for this many minutes they get kicked.
  playerIdleTimeout: 30
  # One of: DEFAULT, FLAT, LEGACY
  levelType: DEFAULT
  # Force clients to use texture packs in the current world
  texturepackRequired: false
  # Used as the server name
  serverName: K8sServer
  # Check accounts against Minecraft account service.
  onlineMode: true
  # Maximum number of threads the server tries to use. If set to 0 or removed then it uses as many as possible.
  maxThreads: 8
  serviceType: ClusterIP
  loadBalancerIP:
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster

## Additional minecraft container environment variables
##
extraEnv: {}

persistence:
  ## minecraft data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  dataDir:
    # Set this to false if you don't care to persist state between restarts.
    enabled: false
    # existingClaim: nil
    Size: 1Gi

podAnnotations: {}

deploymentAnnotations: {}
