apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "proxy.fullname" . }}
  annotations: {{ toYaml .Values.deploymentAnnotations | nindent 4 }}
  labels:
    app: {{ template "proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: {{ template "proxy.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "proxy.fullname" . }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.serviceAcccoutName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy}}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig: 
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers: {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
      - name: {{ template "proxy.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        tty: true
        stdin: true
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          tcpSocket:
            port: 25577
          failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.startupProbe.periodSeconds }}
        {{- end }}
        readinessProbe:
          tcpSocket:
            port: 25577
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        livenessProbe:
          tcpSocket:
            port: 25577
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "1000"
        - name: TYPE
          value: {{ default "" .Values.minecraftProxy.type | quote }}
        {{- if eq .Values.minecraftProxy.type "WATERFALL" }}
        - name: WATERFALL_VERSION
          value: {{ .Values.minecraftProxy.waterfallVersion | quote }}
        - name: WATERFALL_BUILD_ID
          value: {{ .Values.minecraftProxy.waterfallBuildId | quote }}
        {{- else if eq .Values.minecraftProxy.type "VELOCITY" }}
        - name: VELOCITY_VERSION
          value: {{ .Values.minecraftProxy.velocityVersion | quote }}
        {{- end }}
        {{- if .Values.minecraftProxy.jarUrl }}
        - name: BUNGEE_JAR_URL
          value: {{ .Values.minecraftProxy.jarUrl | quote }}
        {{- else if .Values.minecraftProxy.jarFile }}
        - name: BUNGEE_JAR_FILE
          value: {{ .Values.minecraftProxy.jarFile | quote }}
        {{- else }}
        {{- if .Values.minecraftProxy.jenkinsJobId }}
        - name: BUNGEE_JOB_ID
          value: {{ .Values.minecraftProxy.jenkinsJobId }}
        {{- end }}
        {{- if .Values.minecraftProxy.jenkinsBaseUrl }}
        - name: BUNGEE_BASE_URL
          value: {{ .Values.minecraftProxy.jenkinsBaseUrl }}
        {{- end }}
        {{- if .Values.minecraftProxy.jarRevision }}
        - name: BUNGEE_JAR_REVISION
          value: {{ .Values.minecraftProxy.jarRevision }}
        {{- end }}
        {{- end }}
        {{- if .Values.minecraftProxy.plugins }}
        - name: PLUGINS
          value: {{ join "," .Values.minecraftProxy.plugins }}
        {{- end }}
        - name: MEMORY
          value: {{ .Values.minecraftProxy.memory | quote }}
        - name: JVM_OPTS
          value: {{ .Values.minecraftProxy.jvmOpts | quote }}

        {{- if .Values.minecraftProxy.rcon.enabled }}
        - name: ENABLE_RCON
          value: "true"
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minecraftProxy.rcon.existingSecret | default (include "proxy.fullname" .) }}
              key: {{ .Values.minecraftProxy.rcon.secretKey | default "rcon-password" }}
        {{- else }}
        - name: ENABLE_RCON
          value: "false"
        {{- end }}

      {{- range $key, $value := .Values.extraEnv }}
      {{-   if kindIs "map" $value }}
      {{-     if hasKey $value "valueFrom" }}
        - name: {{ $key }}
          valueFrom:
            {{- $value.valueFrom | toYaml | nindent 12 }}
      {{-     end }}
      {{-   else }}
        - name: {{ $key }}
          value: {{ $value | quote }}
      {{-   end }}
      {{- end }}

        ports:
        - name: proxy
          containerPort: 25577
          protocol: TCP
        {{- if .Values.minecraftProxy.rcon.enabled }}
        - name: rcon
          containerPort: 25575
          protocol: TCP
        {{- end }}
        {{- range .Values.minecraftProxy.extraPorts }}
        {{- if .service.enabled }}
        - name: {{ .name }}
          containerPort: {{ .containerPort }}
          {{- if .protocol }}
          protocol: {{ .protocol }}
          {{- else }}
          protocol: TCP
          {{- end }}
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: datadir
          mountPath: /server
        {{- if .Values.minecraftProxy.config }}
        - name: config
          mountPath: {{ .Values.minecraftProxy.configFilePath }}
          subPath: config.yml
        {{- end }}
        {{- range .Values.extraVolumes }}
        {{-   if .volumeMounts }}
        {{-     toYaml .volumeMounts | nindent 8 }}
        {{-   end }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      {{- if .Values.sidecarContainers }}
      {{- toYaml .Values.sidecarContainers | nindent 6 }}
      {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      - name: datadir
      {{- if .Values.persistence.dataDir.enabled }}
        persistentVolumeClaim:
        {{- if .Values.persistence.dataDir.existingClaim }}
          claimName: {{ .Values.persistence.dataDir.existingClaim }}
        {{- else }}
          claimName: {{ template "proxy.fullname" . }}-datadir
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.minecraftProxy.config }}
      - name: config
        configMap:
          name: {{ include "proxy.fullname" . }}-config
      {{- end }}
      {{- range .Values.extraVolumes }}
      {{- toYaml .volumes | nindent 6 }}
      {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
