{{- if default "" .Values.minecraftServer.extraPort.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "minecraft.fullname" . }}-extraPort"
  annotations:
    {{ toYaml .Values.minecraftServer.extraPort.service.annotations | indent 4 }}
  labels:
    app: {{ template "minecraft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
{{- if (or (eq .Values.minecraftServer.extraPort.service.type "ClusterIP") (empty .Values.minecraftServer.extraPort.service.type)) }}
  type: ClusterIP
{{- else if eq .Values.minecraftServer.extraPort.service.type "LoadBalancer" }}
  type: {{ .Values.minecraftServer.extraPort.service.type }}
  {{- if .Values.minecraftServer.extraPort.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.minecraftServer.extraPort.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.minecraftServer.extraPort.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.minecraftServer.extraPort.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.minecraftServer.extraPort.service.type }}
{{- end }}
  {{- if .Values.minecraftServer.extraPort.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.minecraftServer.extraPort.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  - name: extraPort
    port: {{ .Values.minecraftServer.extraPort.service.port }}
    targetPort: extraPort
    protocol: TCP
  selector:
    app: {{ template "minecraft.fullname" . }}
{{- end }}
